# Generated by Django 3.2.12 on 2025-06-01 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlcanceSismico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CambioEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateTimeField()),
                ('fechaHoraInicio', models.DateTimeField(blank=True, null=True)),
                ('fechaHoraFin', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClasificacionSismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kmProfundidadDesde', models.FloatField()),
                ('kmProfundidadHasta', models.FloatField()),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleMuestraSismica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EstacionSismologica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoEstacion', models.CharField(max_length=50, unique=True)),
                ('documentoCertificacionAdq', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=100)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('nroCertificacionAdquisicion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambito', models.CharField(max_length=100)),
                ('nombreEstado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MuestraSismica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detallesMuestras', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muestras_sismicas', to='core.detallemuestrasismica')),
            ],
        ),
        migrations.CreateModel(
            name='OrigenDeGeneracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeDato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.CharField(max_length=100)),
                ('nombreUnidadMedida', models.CharField(max_length=100)),
                ('valorUmbral', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrasena', models.CharField(max_length=128)),
                ('nombreUsuario', models.CharField(max_length=150, unique=True)),
                ('empleado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Sismografo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHoraAdquisicion', models.DateTimeField()),
                ('identificadorSismografo', models.CharField(max_length=100)),
                ('nroSerie', models.IntegerField()),
                ('estacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.estacionsismologica')),
            ],
        ),
        migrations.CreateModel(
            name='SerieTemporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicionAlarma', models.BooleanField()),
                ('fechaHoraInicioRegistroMuestras', models.DateTimeField()),
                ('fechaHoraRegistro', models.DateTimeField()),
                ('frecuenciaMuestreo', models.FloatField()),
                ('muestraSismica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series_temporales', to='core.muestrasismica')),
                ('sismografo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_temporales', to='core.sismografo')),
            ],
        ),
        migrations.CreateModel(
            name='EventoSismico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHoraFin', models.DateTimeField()),
                ('fechaHoraOcurrencia', models.DateTimeField()),
                ('latitudEpicentro', models.FloatField()),
                ('latitudHipocentro', models.FloatField()),
                ('longitudEpicentro', models.FloatField()),
                ('longitudHipocentro', models.FloatField()),
                ('valorMagnitud', models.FloatField()),
                ('alcanceSismico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_alcance', to='core.alcancesismico')),
                ('analistaSuperior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_analista_superior', to='core.empleado')),
                ('cambioEstado', models.ManyToManyField(related_name='eventos_cambios_estado', to='core.CambioEstado')),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_clasificados', to='core.clasificacionsismo')),
                ('estadoActual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_actuales', to='core.estado')),
                ('origenGeneracion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_origen', to='core.origendegeneracion')),
                ('serieTemporal', models.ManyToManyField(related_name='eventos', to='core.SerieTemporal')),
            ],
        ),
        migrations.AddField(
            model_name='detallemuestrasismica',
            name='tipoDato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_muestras_sismicas', to='core.tipodedato'),
        ),
        migrations.AddField(
            model_name='cambioestado',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empleado'),
        ),
        migrations.AddField(
            model_name='cambioestado',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estado'),
        ),
        migrations.AddField(
            model_name='cambioestado',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cambios_estado', to='core.eventosismico'),
        ),
    ]
