# Generated by Django 3.2.12 on 2025-06-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestrasismica',
            name='fechaHoraMuestra',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
