# Generated by Django 5.2.1 on 2025-05-28 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_muestrasismica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cambioestado',
            name='evento',
        ),
    ]
