# Generated by Django 5.2.1 on 2025-06-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='sismografo',
            name='series_temporales',
            field=models.ManyToManyField(blank=True, related_name='sismografos', to='core.serietemporal'),
        ),
    ]
