# Generated by Django 5.2.1 on 2025-05-31 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_cambioestado_evento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlcanceSismo',
            new_name='AlcanceSismico',
        ),
        migrations.RenameField(
            model_name='eventosismico',
            old_name='alcanceSismo',
            new_name='alcanceSismico',
        ),
    ]
