# Generated by Django 3.2.12 on 2025-05-31 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_cambioestado_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cambioestado',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cambios_estado', to='core.eventosismico'),
        ),
    ]
