# Generated by Django 3.2.12 on 2025-05-31 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cambioestado_evento'),
        ('core', '0004_rename_alcancesismo_alcancesismico_and_more'),
    ]

    operations = [
    ]
