# Generated by Django 5.2.1 on 2025-06-09 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sismografo_series_temporales'),
    ]

    operations = [
    ]
