# Generated by Django 5.2.1 on 2025-11-08 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20250609_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoDetectado',
            fields=[
                ('estado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.estado')),
            ],
            bases=('core.estado',),
        ),
        migrations.CreateModel(
            name='Bloqueado',
            fields=[
                ('estado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.estado')),
            ],
            bases=('core.estado',),
        ),
        migrations.CreateModel(
            name='Confirmado',
            fields=[
                ('estado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.estado')),
            ],
            bases=('core.estado',),
        ),
        migrations.CreateModel(
            name='Derivado',
            fields=[
                ('estado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.estado')),
            ],
            bases=('core.estado',),
        ),
        migrations.CreateModel(
            name='PendienteDeRevision',
            fields=[
                ('estado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.estado')),
            ],
            bases=('core.estado',),
        ),
        migrations.CreateModel(
            name='Rechazado',
            fields=[
                ('estado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.estado')),
            ],
            bases=('core.estado',),
        ),
    ]
