# Generated by Django 5.2.1 on 2025-11-09 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_estado_polymorphic_ctype'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoConfirmado',
            fields=[
                ('estado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.estado')),
            ],
            bases=('core.estado',),
        ),
        migrations.CreateModel(
            name='Cerrado',
            fields=[
                ('estado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.estado')),
            ],
            bases=('core.estado',),
        ),
        migrations.CreateModel(
            name='EventoSinRevision',
            fields=[
                ('estado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.estado')),
            ],
            bases=('core.estado',),
        ),
        migrations.CreateModel(
            name='PendienteDeCierre',
            fields=[
                ('estado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.estado')),
            ],
            bases=('core.estado',),
        ),
    ]
